"""
Tests using real files from PR #161 (openid/publication) as originally submitted.

PR #161 adds two specs in ekyc-ida/:
- openid-connect-4-identity-assurance-1_0-17.html (Draft 17 - no errata language)
- openid-ida-verified-claims-1_0-03.html (Draft 03 - no errata language)

Both are generated by xml2rfc. A final already exists for both specs,
so these should have been titled as draft errata but weren't.
Copies of the original PR files are stored in tests/fixtures/.
"""
from __future__ import annotations

import os
import re
import sys

import pytest

_TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
if _TESTS_DIR not in sys.path:
    sys.path.insert(0, _TESTS_DIR)

_REPO_ROOT = os.path.join(_TESTS_DIR, "..")
sys.path.insert(0, _REPO_ROOT)

from e2e_helpers import create_test_repo, run_python_script  # noqa: E402
import spec_validator  # noqa: E402

pytestmark = pytest.mark.e2e

FIXTURES_DIR = os.path.join(_TESTS_DIR, "fixtures")

_PR161_PATHS = [
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.html",
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.md",
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.xml",
    "ekyc-ida/openid-ida-verified-claims-1_0-03.html",
    "ekyc-ida/openid-ida-verified-claims-1_0-03.md",
    "ekyc-ida/openid-ida-verified-claims-1_0-03.xml",
]


@pytest.fixture(scope="module")
def pr161_files():
    """Load original PR #161 files from fixtures."""
    files = {}
    for path in _PR161_PATHS:
        fixture_path = os.path.join(FIXTURES_DIR, os.path.basename(path))
        with open(fixture_path, "r", encoding="utf-8") as f:
            files[path] = f.read()
    return files


# ===================================================================
# Unit-level tests: validate individual checks against real files
# ===================================================================


class TestIDASpec:
    """Tests for openid-connect-4-identity-assurance-1_0-17.html.

    This spec was submitted as a plain DRAFT but a final already exists,
    so it should have been a DRAFT_ERRATA. The title says 'draft 17'
    without any errata language.
    """

    @pytest.fixture(autouse=True)
    def setup(self, pr161_files):
        self.content = pr161_files[
            "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.html"
        ]
        self.filename = "openid-connect-4-identity-assurance-1_0-17.html"

    def test_filename_state_is_draft(self):
        result = spec_validator.filename_state(self.filename)
        assert result["state"] == "DRAFT"

    def test_content_state_is_draft(self):
        """Title says 'draft 17' without errata language, so state is DRAFT."""
        result = spec_validator.content_state(self.content)
        assert result["state"] == "DRAFT"

    def test_title_matches_h1(self):
        result = spec_validator.content_title(self.content)
        assert result["match"] is True

    def test_filename_matches_content(self):
        result = spec_validator.content_filename_match(self.content, self.filename)
        assert result["match"] is True

    def test_has_history(self):
        result = spec_validator.content_history(self.content)
        assert result["history_present"] is True

    def test_has_authors(self):
        result = spec_validator.content_authors(self.content)
        assert len(result["authors"]) >= 1

    def test_has_notices(self):
        result = spec_validator.content_notices(self.content)
        assert result["notices"] is True

    def test_has_license_text(self):
        result = spec_validator.content_notices(self.content)
        assert result["license_text_present"] is True

    def test_copyright_year_is_2026(self):
        result = spec_validator.content_notices(self.content)
        assert result["copyright_year"] == 2026

    def test_abstract_missing_due_to_xml2rfc_format(self):
        """xml2rfc-generated HTML doesn't have a standard Abstract heading."""
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ABSTRACT"] is False

    def test_introduction_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["INTRODUCTION"] is True

    def test_normative_references_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["NORMATIVE_REFERENCES"] is True

    def test_security_considerations_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["SECURITY"] is True

    def test_acknowledgements_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ACKNOWLEDGEMENTS"] is True

    def test_md_has_file_includes(self, pr161_files):
        """The .md source has <{{examples/...}} file includes."""
        md = pr161_files["ekyc-ida/openid-connect-4-identity-assurance-1_0-17.md"]
        assert "<{{" in md


class TestVerifiedClaimsSpec:
    """Tests for openid-ida-verified-claims-1_0-03.html."""

    @pytest.fixture(autouse=True)
    def setup(self, pr161_files):
        self.content = pr161_files[
            "ekyc-ida/openid-ida-verified-claims-1_0-03.html"
        ]
        self.filename = "openid-ida-verified-claims-1_0-03.html"

    def test_filename_state_is_draft(self):
        result = spec_validator.filename_state(self.filename)
        assert result["state"] == "DRAFT"

    def test_content_state_is_draft(self):
        result = spec_validator.content_state(self.content)
        assert result["state"] == "DRAFT"

    def test_title_matches_h1(self):
        result = spec_validator.content_title(self.content)
        assert result["match"] is True

    def test_has_history(self):
        result = spec_validator.content_history(self.content)
        assert result["history_present"] is True

    def test_has_authors(self):
        result = spec_validator.content_authors(self.content)
        assert len(result["authors"]) >= 1

    def test_has_notices(self):
        result = spec_validator.content_notices(self.content)
        assert result["notices"] is True

    def test_has_license_text(self):
        result = spec_validator.content_notices(self.content)
        assert result["license_text_present"] is True

    def test_abstract_missing_due_to_xml2rfc_format(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ABSTRACT"] is False

    def test_acknowledgements_detected(self):
        """Uses 'Acknowledgement' (singular) inside 'Annex A (Informative)' — now detected."""
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ACKNOWLEDGEMENTS"] is True

    def test_introduction_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["INTRODUCTION"] is True

    def test_security_considerations_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["SECURITY"] is True

    def test_md_has_file_includes(self, pr161_files):
        md = pr161_files["ekyc-ida/openid-ida-verified-claims-1_0-03.md"]
        assert "<{{" in md


# ===================================================================
# E2E test: run process.py against the PR files
# ===================================================================


def test_process_py_on_pr161(tmp_path, pr161_files):
    """Run process.py against the original PR #161 files.

    Expected failures (per spec):
    - Both: .md references external files but no .zip
    - Both: previous version included .zip but this submission does not
    - Both: final spec already exists (title should use errata language)
    - Both: references check fails (openid.net/wg/ekyc-ida/references/ returns 404)
    - Both: missing ABSTRACT (xml2rfc format gap)
    """
    # Seed CSV with the final specs (so "final already exists" check fires)
    # but without the draft filenames themselves (so duplicate check passes).
    csv_content = (
        "Filename,Date,Size\n"
        "openid-connect-4-identity-assurance-1_0-final.html,2025-06-01,300K\n"
        "openid-connect-4-identity-assurance-1_0-16.html,2025-03-01,280K\n"
        "openid-connect-4-identity-assurance-1_0-16.zip,2025-03-01,500K\n"
        "openid-ida-verified-claims-1_0-final.html,2025-06-01,150K\n"
        "openid-ida-verified-claims-1_0-02.html,2025-01-15,140K\n"
        "openid-ida-verified-claims-1_0-02.zip,2025-01-15,300K\n"
    )
    repo_path, scripts_path = create_test_repo(
        tmp_path, pr161_files, spec_list_csv_content=csv_content,
    )

    # Fixture specs are published 2026-03-26 — pin "today" within the 10-day
    # window so the date check doesn't fail as wall-clock time advances.
    result = run_python_script(
        "process.py", repo_path, scripts_path,
        env_overrides={"OVERRIDE_TODAY": "2026-03-30"},
    )

    assert result.returncode == 1, (
        f"Expected exit 1 but got {result.returncode}.\n"
        f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )

    clean = re.sub(r'\x1b\[[0-9;]*m', '', result.stdout)

    # Extract all FAIL lines
    fail_lines = [line.strip() for line in clean.splitlines() if line.strip().startswith("FAIL:")]

    # Expected failures
    expected_fails = [
        "references external files",                    # both: .md has includes, no .zip
        "Previous version",                             # both: prev version had .zip
        "Final spec already exists",                    # both: should use errata title
        "Problem with References",                      # both: 404 on wg references URL
        "Missing sections: ABSTRACT",                   # both: xml2rfc format gap
        "did not pass all checks",                      # both: summary line
    ]

    # Check every FAIL line matches at least one expected pattern
    unexpected = []
    for fail in fail_lines:
        if not any(exp in fail for exp in expected_fails):
            unexpected.append(fail)

    assert not unexpected, (
        f"Unexpected failures found:\n"
        + "\n".join(f"  {f}" for f in unexpected)
        + f"\n\nAll FAIL lines:\n"
        + "\n".join(f"  {f}" for f in fail_lines)
    )

    # Verify key expected failures are present
    assert any("references external files" in f for f in fail_lines)
    assert any("Previous version" in f for f in fail_lines)
    assert any("Final spec already exists" in f for f in fail_lines)
    assert any("Missing sections: ABSTRACT" in f for f in fail_lines)


# ===================================================================
# Publish test: DRAFT_ERRATA with patched title
# ===================================================================


def test_publish_draft_errata_ida_spec(tmp_path, pr161_files):
    """Simulate publishing the IDA spec with a corrected errata title.

    Patch the title to include errata language, then verify publish.py
    creates only versioned copies (not overwriting the unversioned final).
    """
    ida_html = pr161_files[
        "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.html"
    ]

    original_title = "OpenID Connect for Identity Assurance 1.0 - draft 17"
    errata_title = "OpenID Connect for Identity Assurance 1.0 incorporating errata set 1 - draft 17"
    patched_html = ida_html.replace(original_title, errata_title)

    state = spec_validator.content_state(patched_html)
    assert state["state"] == "DRAFT_ERRATA"

    ida_files = {}
    for k, v in pr161_files.items():
        if "identity-assurance" in k:
            if k.endswith(".html"):
                ida_files[k] = patched_html
            else:
                ida_files[k] = v

    csv_content = "Filename,Date,Size\n"
    repo_path, scripts_path = create_test_repo(
        tmp_path, ida_files, spec_list_csv_content=csv_content,
    )
    to_publish = repo_path / "to-publish"
    to_publish.mkdir(exist_ok=True)

    result = run_python_script("publish.py", repo_path, scripts_path)

    assert result.returncode == 0, (
        f"Expected exit 0 but got {result.returncode}.\n"
        f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )
    assert "DRAFT_ERRATA" in result.stdout

    published = {p.name for p in to_publish.iterdir()}

    # Versioned copies SHOULD exist
    assert "openid-connect-4-identity-assurance-1_0-17.html" in published
    assert "openid-connect-4-identity-assurance-1_0-17.md" in published
    assert "openid-connect-4-identity-assurance-1_0-17.xml" in published

    # Unversioned copies SHOULD NOT exist (final holds that URL)
    assert "openid-connect-4-identity-assurance-1_0.html" not in published, (
        "Draft errata should not overwrite the unversioned final URL"
    )
