"""
End-to-end test using real files from PR #161 (openid/publication).

PR #161 adds two specs in ekyc-ida/:
- openid-connect-4-identity-assurance-1_0-17.html (Draft 17)
- openid-ida-verified-claims-1_0-03.html (Draft 03)

Both are generated by xml2rfc and have accompanying .md and .xml source files.
This test runs the full process.py validation pipeline against them.
"""

from __future__ import annotations

import os
import subprocess
import sys

import pytest

_TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
if _TESTS_DIR not in sys.path:
    sys.path.insert(0, _TESTS_DIR)

_REPO_ROOT = os.path.join(_TESTS_DIR, "..")
sys.path.insert(0, _REPO_ROOT)

from pathlib import Path  # noqa: E402
from conftest import _build_spec_html  # noqa: E402
from e2e_helpers import create_test_repo, run_python_script  # noqa: E402
import spec_validator  # noqa: E402

pytestmark = pytest.mark.e2e

# Path to the publication repo where we fetched the PR branch
_PUBLICATION_REPO = "/Users/joseph/Documents/openid/publication"
_PR_BRANCH = "origin/propose/openid-connect-4-identity-assurance-1_0-17"

_PR_FILES = {
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.html": None,
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.md": None,
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.xml": None,
    "ekyc-ida/openid-ida-verified-claims-1_0-03.html": None,
    "ekyc-ida/openid-ida-verified-claims-1_0-03.md": None,
    "ekyc-ida/openid-ida-verified-claims-1_0-03.xml": None,
}


def _load_pr_files():
    """Load actual file contents from the PR branch in the publication repo."""
    files = {}
    for path in _PR_FILES:
        result = subprocess.run(
            ["git", "show", f"{_PR_BRANCH}:{path}"],
            cwd=_PUBLICATION_REPO,
            capture_output=True,
        )
        if result.returncode != 0:
            pytest.skip(f"Could not load {path} from {_PR_BRANCH}")
        files[path] = result.stdout  # bytes, since HTML may have encoding issues
    return files


@pytest.fixture(scope="module")
def pr161_files():
    """Load PR #161 files once for all tests in this module."""
    return _load_pr_files()


# ===================================================================
# Unit-level tests: validate individual checks against real files
# ===================================================================


class TestIDASpec:
    """Tests for openid-connect-4-identity-assurance-1_0-17.html."""

    @pytest.fixture(autouse=True)
    def setup(self, pr161_files):
        self.content = pr161_files[
            "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.html"
        ].decode("utf-8")
        self.filename = "openid-connect-4-identity-assurance-1_0-17.html"

    def test_filename_state_is_draft(self):
        result = spec_validator.filename_state(self.filename)
        assert result["state"] == "DRAFT"

    def test_content_state_is_draft(self):
        result = spec_validator.content_state(self.content)
        assert result["state"] == "DRAFT"

    def test_title_matches_h1(self):
        result = spec_validator.content_title(self.content)
        assert result["match"] is True

    def test_filename_matches_content(self):
        result = spec_validator.content_filename_match(self.content, self.filename)
        assert result["match"] is True

    def test_has_history(self):
        result = spec_validator.content_history(self.content)
        assert result["history_present"] is True

    def test_has_authors(self):
        result = spec_validator.content_authors(self.content)
        assert len(result["authors"]) >= 1

    def test_has_notices(self):
        result = spec_validator.content_notices(self.content)
        assert result["notices"] is True

    def test_has_license_text(self):
        result = spec_validator.content_notices(self.content)
        assert result["license_text_present"] is True

    def test_copyright_year_is_2026(self):
        result = spec_validator.content_notices(self.content)
        assert result["copyright_year"] == 2026

    def test_abstract_missing_due_to_xml2rfc_format(self):
        """xml2rfc-generated HTML doesn't have a standard Abstract heading.
        This documents a known pattern gap in the validator."""
        result = spec_validator.content_struct(self.content)
        # This SHOULD be True but the validator can't detect it
        assert result["structure"]["ABSTRACT"] is False

    def test_introduction_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["INTRODUCTION"] is True

    def test_normative_references_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["NORMATIVE_REFERENCES"] is True

    def test_security_considerations_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["SECURITY"] is True

    def test_acknowledgements_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ACKNOWLEDGEMENTS"] is True

    def test_publication_date_recent(self):
        result, _ = spec_validator.content_date(self.content)
        assert result["date"] == "2026-03-26"


class TestVerifiedClaimsSpec:
    """Tests for openid-ida-verified-claims-1_0-03.html."""

    @pytest.fixture(autouse=True)
    def setup(self, pr161_files):
        self.content = pr161_files[
            "ekyc-ida/openid-ida-verified-claims-1_0-03.html"
        ].decode("utf-8")
        self.filename = "openid-ida-verified-claims-1_0-03.html"

    def test_filename_state_is_draft(self):
        result = spec_validator.filename_state(self.filename)
        assert result["state"] == "DRAFT"

    def test_content_state_is_draft(self):
        result = spec_validator.content_state(self.content)
        assert result["state"] == "DRAFT"

    def test_title_matches_h1(self):
        result = spec_validator.content_title(self.content)
        assert result["match"] is True

    def test_filename_matches_content(self):
        result = spec_validator.content_filename_match(self.content, self.filename)
        assert result["match"] is True

    def test_has_history(self):
        result = spec_validator.content_history(self.content)
        assert result["history_present"] is True

    def test_has_authors(self):
        result = spec_validator.content_authors(self.content)
        assert len(result["authors"]) >= 1

    def test_has_notices(self):
        result = spec_validator.content_notices(self.content)
        assert result["notices"] is True

    def test_has_license_text(self):
        result = spec_validator.content_notices(self.content)
        assert result["license_text_present"] is True

    def test_abstract_missing_due_to_xml2rfc_format(self):
        """Same xml2rfc pattern gap as the IDA spec."""
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ABSTRACT"] is False

    def test_acknowledgements_missing_due_to_nonstandard_heading(self):
        """This spec uses 'Acknowledgement' (singular) inside 'Annex A (Informative)',
        which doesn't match the validator's ACKNOWLEDGEMENTS pattern."""
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ACKNOWLEDGEMENTS"] is False

    def test_introduction_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["INTRODUCTION"] is True

    def test_security_considerations_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["SECURITY"] is True


# ===================================================================
# E2E test: run process.py against the PR files
# ===================================================================


@pytest.mark.skipif(
    not os.path.isdir(_PUBLICATION_REPO),
    reason="publication repo not available",
)
def test_process_py_on_pr161(tmp_path, pr161_files):
    """Run process.py against the PR #161 files and check what fails.

    We expect failures because:
    1. ABSTRACT is not detected (xml2rfc format gap)
    2. Verified Claims spec has non-standard Acknowledgements heading
    3. No .zip files included (issue #166 mentions this)
    """
    # Decode bytes to str for create_test_repo
    str_files = {
        k: v.decode("utf-8") if isinstance(v, bytes) else v
        for k, v in pr161_files.items()
    }
    repo_path, scripts_path = create_test_repo(tmp_path, str_files)

    result = run_python_script("process.py", repo_path, scripts_path)

    # We expect process.py to fail because of missing structure
    assert result.returncode == 1, (
        f"Expected exit 1 (structure failures) but got {result.returncode}.\n"
        f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )
    # The structure check should flag the missing ABSTRACT
    assert "Problem with structure" in result.stdout


# ===================================================================
# Publish test: what files does publish.py create for a draft errata?
# ===================================================================


@pytest.mark.skipif(
    not os.path.isdir(_PUBLICATION_REPO),
    reason="publication repo not available",
)
def test_publish_draft_errata_ida_spec(tmp_path, pr161_files):
    """Simulate publishing PR #161's IDA spec with a corrected errata title.

    Since a final already exists, the spec should be titled as a draft errata.
    publish.py should create only versioned copies (not overwrite the
    unversioned final URL).

    Files expected in to-publish/:
    - openid-connect-4-identity-assurance-1_0-17.html  (versioned)
    - openid-connect-4-identity-assurance-1_0-17.md    (versioned)
    - openid-connect-4-identity-assurance-1_0-17.xml   (versioned)
    NOT expected:
    - openid-connect-4-identity-assurance-1_0.html     (unversioned - belongs to final)
    """
    # Take the real HTML and patch the title to be a draft errata
    ida_html = pr161_files[
        "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.html"
    ]
    if isinstance(ida_html, bytes):
        ida_html = ida_html.decode("utf-8")

    # Patch the title and h1 to include errata language
    original_title = "OpenID Connect for Identity Assurance 1.0 - draft 17"
    errata_title = "OpenID Connect for Identity Assurance 1.0 incorporating errata set 1 - draft 17"
    patched_html = ida_html.replace(original_title, errata_title)

    # Verify the patch worked
    state = spec_validator.content_state(patched_html)
    assert state["state"] == "DRAFT_ERRATA", (
        f"Expected DRAFT_ERRATA after title patch, got {state['state']}"
    )

    str_files = {}
    for k, v in pr161_files.items():
        content = v.decode("utf-8") if isinstance(v, bytes) else v
        # Only include the IDA spec (not the verified claims spec)
        if "identity-assurance" in k:
            if k.endswith(".html"):
                str_files[k] = patched_html
            else:
                str_files[k] = content

    repo_path, scripts_path = create_test_repo(tmp_path, str_files)

    # Create the to-publish directory
    to_publish = repo_path / "to-publish"
    to_publish.mkdir(exist_ok=True)

    result = run_python_script("publish.py", repo_path, scripts_path)

    assert result.returncode == 0, (
        f"Expected exit 0 but got {result.returncode}.\n"
        f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )
    assert "DRAFT_ERRATA" in result.stdout

    published = {p.name for p in to_publish.iterdir()}
    print(f"Files in to-publish/: {sorted(published)}")

    # Versioned copies SHOULD exist
    assert "openid-connect-4-identity-assurance-1_0-17.html" in published
    assert "openid-connect-4-identity-assurance-1_0-17.md" in published
    assert "openid-connect-4-identity-assurance-1_0-17.xml" in published

    # Unversioned copies SHOULD NOT exist (final holds that URL)
    assert "openid-connect-4-identity-assurance-1_0.html" not in published, (
        "Draft errata should not overwrite the unversioned final URL"
    )
    assert "openid-connect-4-identity-assurance-1_0.md" not in published
    assert "openid-connect-4-identity-assurance-1_0.xml" not in published
