"""
Tests using real files from PR #161 (openid/publication).

PR #161 adds two specs in ekyc-ida/:
- openid-connect-4-identity-assurance-1_0-17.html (Draft Errata)
- openid-ida-verified-claims-1_0-03.html (Draft Errata)

Both are generated by xml2rfc and have accompanying .md and .xml source files.
Copies of the PR files are stored in tests/fixtures/ for stability.
"""
from __future__ import annotations

import os
import re
import sys

import pytest

_TESTS_DIR = os.path.dirname(os.path.abspath(__file__))
if _TESTS_DIR not in sys.path:
    sys.path.insert(0, _TESTS_DIR)

_REPO_ROOT = os.path.join(_TESTS_DIR, "..")
sys.path.insert(0, _REPO_ROOT)

from pathlib import Path  # noqa: E402
from conftest import _build_spec_html  # noqa: E402
from e2e_helpers import create_test_repo, run_python_script  # noqa: E402
import spec_validator  # noqa: E402

pytestmark = pytest.mark.e2e

FIXTURES_DIR = os.path.join(_TESTS_DIR, "fixtures")

_PR161_FILES = {
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.html": None,
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.md": None,
    "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.xml": None,
    "ekyc-ida/openid-ida-verified-claims-1_0-03.html": None,
    "ekyc-ida/openid-ida-verified-claims-1_0-03.md": None,
    "ekyc-ida/openid-ida-verified-claims-1_0-03.xml": None,
}


@pytest.fixture(scope="module")
def pr161_files():
    """Load PR #161 files from fixtures."""
    files = {}
    for path in _PR161_FILES:
        fixture_path = os.path.join(FIXTURES_DIR, os.path.basename(path))
        with open(fixture_path, "r", encoding="utf-8") as f:
            files[path] = f.read()
    return files


# ===================================================================
# Unit-level tests: validate individual checks against real files
# ===================================================================


class TestIDASpec:
    """Tests for openid-connect-4-identity-assurance-1_0-17.html."""

    @pytest.fixture(autouse=True)
    def setup(self, pr161_files):
        self.content = pr161_files[
            "ekyc-ida/openid-connect-4-identity-assurance-1_0-17.html"
        ]
        self.filename = "openid-connect-4-identity-assurance-1_0-17.html"

    def test_filename_state_is_draft(self):
        result = spec_validator.filename_state(self.filename)
        assert result["state"] == "DRAFT"

    def test_content_state_is_draft_errata(self):
        result = spec_validator.content_state(self.content)
        assert result["state"] == "DRAFT_ERRATA"

    def test_title_matches_h1(self):
        result = spec_validator.content_title(self.content)
        assert result["match"] is True

    def test_has_history(self):
        result = spec_validator.content_history(self.content)
        assert result["history_present"] is True

    def test_has_authors(self):
        result = spec_validator.content_authors(self.content)
        assert len(result["authors"]) >= 1

    def test_has_notices(self):
        result = spec_validator.content_notices(self.content)
        assert result["notices"] is True

    def test_has_license_text(self):
        result = spec_validator.content_notices(self.content)
        assert result["license_text_present"] is True

    def test_copyright_year(self):
        result = spec_validator.content_notices(self.content)
        assert result["copyright_year"] == 2026

    def test_abstract_missing_due_to_xml2rfc_format(self):
        """xml2rfc-generated HTML doesn't have a standard Abstract heading."""
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ABSTRACT"] is False

    def test_introduction_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["INTRODUCTION"] is True

    def test_normative_references_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["NORMATIVE_REFERENCES"] is True

    def test_security_considerations_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["SECURITY"] is True

    def test_acknowledgements_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ACKNOWLEDGEMENTS"] is True


class TestVerifiedClaimsSpec:
    """Tests for openid-ida-verified-claims-1_0-03.html."""

    @pytest.fixture(autouse=True)
    def setup(self, pr161_files):
        self.content = pr161_files[
            "ekyc-ida/openid-ida-verified-claims-1_0-03.html"
        ]
        self.filename = "openid-ida-verified-claims-1_0-03.html"

    def test_filename_state_is_draft(self):
        result = spec_validator.filename_state(self.filename)
        assert result["state"] == "DRAFT"

    def test_content_state_is_draft_errata(self):
        result = spec_validator.content_state(self.content)
        assert result["state"] == "DRAFT_ERRATA"

    def test_title_matches_h1(self):
        result = spec_validator.content_title(self.content)
        assert result["match"] is True

    def test_has_history(self):
        result = spec_validator.content_history(self.content)
        assert result["history_present"] is True

    def test_has_authors(self):
        result = spec_validator.content_authors(self.content)
        assert len(result["authors"]) >= 1

    def test_has_notices(self):
        result = spec_validator.content_notices(self.content)
        assert result["notices"] is True

    def test_has_license_text(self):
        result = spec_validator.content_notices(self.content)
        assert result["license_text_present"] is True

    def test_abstract_missing_due_to_xml2rfc_format(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ABSTRACT"] is False

    def test_acknowledgements_missing_due_to_nonstandard_heading(self):
        """Uses 'Acknowledgement' (singular) in 'Annex A (Informative)'."""
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["ACKNOWLEDGEMENTS"] is False

    def test_introduction_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["INTRODUCTION"] is True

    def test_security_considerations_present(self):
        result = spec_validator.content_struct(self.content)
        assert result["structure"]["SECURITY"] is True


# ===================================================================
# E2E test: run process.py against the PR files
# ===================================================================


def test_process_py_on_pr161(tmp_path, pr161_files):
    """Run process.py against the PR #161 files and check what fails.

    Expected failures (per spec):
    - Both: .md references external files but no .zip
    - Both: previous version included .zip but this submission does not
    - Both: references check fails (openid.net/wg/ekyc-ida/references/ returns 404)
    - Both: missing ABSTRACT (xml2rfc format gap)
    - Verified Claims only: also missing ACKNOWLEDGEMENTS (non-standard heading)
    """
    repo_path, scripts_path = create_test_repo(tmp_path, pr161_files)

    result = run_python_script("process.py", repo_path, scripts_path)

    assert result.returncode == 1, (
        f"Expected exit 1 but got {result.returncode}.\n"
        f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )

    clean = re.sub(r'\x1b\[[0-9;]*m', '', result.stdout)

    # Extract all FAIL lines
    fail_lines = [line.strip() for line in clean.splitlines() if line.strip().startswith("FAIL:")]

    # Expected failures
    expected_fails = [
        "references external files",                    # both: .md has includes, no .zip
        "Previous version",                             # both: prev version had .zip
        "Problem with References",                      # both: 404 on wg references URL
        "Missing sections: ABSTRACT",                   # IDA: xml2rfc format gap
        "Missing sections: ABSTRACT, ACKNOWLEDGEMENTS", # Verified Claims: also missing ack
        "did not pass all checks",                      # both: summary line
    ]

    # Check every FAIL line matches at least one expected pattern
    unexpected = []
    for fail in fail_lines:
        if not any(exp in fail for exp in expected_fails):
            unexpected.append(fail)

    assert not unexpected, (
        f"Unexpected failures found:\n"
        + "\n".join(f"  {f}" for f in unexpected)
        + f"\n\nAll FAIL lines:\n"
        + "\n".join(f"  {f}" for f in fail_lines)
    )

    # Verify key expected failures are present
    assert any("references external files" in f for f in fail_lines)
    assert any("Previous version" in f for f in fail_lines)
    assert any("Missing sections: ABSTRACT" in f for f in fail_lines)


# ===================================================================
# Publish test: what files does publish.py create for a draft errata?
# ===================================================================


def test_publish_draft_errata_ida_spec(tmp_path, pr161_files):
    """Publish PR #161's IDA spec (now titled as draft errata).

    publish.py should create only versioned copies (not overwrite the
    unversioned final URL).
    """
    # Only include the IDA spec
    ida_files = {
        k: v for k, v in pr161_files.items()
        if "identity-assurance" in k
    }

    repo_path, scripts_path = create_test_repo(tmp_path, ida_files)

    # Create the to-publish directory
    to_publish = repo_path / "to-publish"
    to_publish.mkdir(exist_ok=True)

    result = run_python_script("publish.py", repo_path, scripts_path)

    assert result.returncode == 0, (
        f"Expected exit 0 but got {result.returncode}.\n"
        f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
    )
    assert "DRAFT_ERRATA" in result.stdout

    published = {p.name for p in to_publish.iterdir()}

    # Versioned copies SHOULD exist
    assert "openid-connect-4-identity-assurance-1_0-17.html" in published
    assert "openid-connect-4-identity-assurance-1_0-17.md" in published
    assert "openid-connect-4-identity-assurance-1_0-17.xml" in published

    # Unversioned copies SHOULD NOT exist (final holds that URL)
    assert "openid-connect-4-identity-assurance-1_0.html" not in published, (
        "Draft errata should not overwrite the unversioned final URL"
    )
